project:
  type: website

website:
  title: "Steven Lu Chen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: "My Resume"
      - href: projects.qmd
        text: "Projects"
      - href: about.qmd
        text: "About Me"
      - href: contact.qmd
        text: "Contact"
format:
  html:
    theme: flatly
    css: styles.css
    toc: false



